services:
  berkah-alam:
    build:
      context: /home/storage/apps/berkah-alam
      dockerfile: Dockerfile
    image: berkah-alam:latest
    container_name: berkah-alam
    restart: unless-stopped
    ports:
      - "3005:80"
    networks:
      - homelab

networks:
  homelab:
    external: true
